# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.35.2/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-operator
  namespace: cfd-system
spec:
  selector: {}
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: cloudflared-operator
      securityContext:
        runAsNonRoot: true

      containers:
        - name: operator
          image: ghcr.io/tehlordvortex/cloudflared-operator/operator
          env:
            - name: RUST_LOG
              value: info
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
