apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/tehlordvortex/cloudflared-operator/operator
    newTag: v0.0.1

labels:
  - pairs:
      app.kubernetes.io/name: cloudflared-operator
      app.kubernetes.io/version: v0.0.1
    includeSelectors: true
    includeTemplates: true

resources:
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml
  - deployment.yaml
