# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.35.2/role.json
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudflared-operator
  namespace: cfd-system
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "create", "patch", "deletecollection"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "create", "patch", "deletecollection"]
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints"]
    verbs: ["get", "create", "patch", "deletecollection"]
